<?php
   define(LANG_CANT_GET_ADDRESS,'Can`t get bitcoin address, try again later');
   define(LANG_GET_ADDRESS_AGAIN,'Get payment address');
   define(LANG_BALANCE_SUCCESS_CHECKOUT,'Checkout success!');
   define(LANG_BALANCE_ERROR_CHECKOUT, 'Checkout error!');
   define(LANG_BALANCE_NOTHING_CHECKOUT,'Nothing to checkout, zero BTC balance!');
   define(LANG_CANT_GET_BALANCE,'Can`t get balance, try again later.');

// Test
   define(LANG_TEST_COINS_OK,'Test coins enrolled');
   define(LANG_TEST_NOCOINS,'There are no more test coins ');
   define(CANT_USE_MAIN_ACC,'You can`t use this account, sorry.');
   
// Templates

 //index.tpl
 define(SM_YOUR_ACCOUNT,'Your account');
 define(SM_CHANGE_NAME,'Change');
 define(SM_YOUR_BITPAY_ADDRES,'Your BitCoin addres');
 define(SM_YOUR_CURRENT_BTC_BALANCE,'Your current BTC balance');
 define(SM_YOUR_CURRENT_USD_BALANCE,'Your current USD balance');
 define(SM_REFRESH_BTC_BALANCE,'Refresh BTC balance');
 define(SM_REFRESH_BTC_BALANCE_SIGN,'Autorefresh once a minute.');
 
 define(SM_REFRESH_USD_BALANCE,'Refresh USD balance');
 define(SM_GIVE_ME_TEST_COINS,'Enroll some test coins');
 define(SM_GIVE_ME_TEST_COINS2,'(Переводятся внутренним переводом из аккаунта, который находится на этом же кошельке)');
 define(SM_SHOW_ALL_ACCOUNTS,'Show all account balances on the wallet');
 define(SM_REFRESH_TRANSACTIONS,'Refresh transactions');
 define(SM_TRANSACTIONS_LIST,'Transactions list:');
 define(SM_DO_CHECKOUT,'Checkout BTC to USD');
 define(SM_DO_CHECKOUT_TITLE,'Resets BTC balance and converts it into USD balance the current, specified in the settings, exchange rate');
 define(SM_SM_GIVE_ME_TEST_COINS_TITLE,'Used for demonstration purposes only, it sends some BTC from main consolidated account into the current');
 
 
 define(SM_CONFIRMED,'Confirmed');
 define(SM_UNCONFIRMED,'Waiting confirmation');
 
 define(SM_COPY_TO_CLIPBOARD,'Copy to clipboard');
 
 //user_name.tpl
 define(SM_ENTER_YOUR_NAME,'Enter your name:');
 
 //transactions
 define(SM_DATE,'Date');
 define(SM_OPERATION,'Operation');
 define(SM_FROM,'From');
 define(SM_TO,'To');
 define(SM_SUM,'Amount');
 define(SM_COMMENT,'Comment');
 define(SM_CONF,'Confirmations');
 define(SM_TRANS,'Transaction');
 define(SM_INTERNAL_MOVE,'Internal move');
 define(SM_INTERNAL_REFILL,'External refill');
 
 //accounts.tpl
 define(SM_ALL_BTC_BALANCE,'Account balances for all accounts on this wallet:');
 define(SM_ACCOUNT,'Account');
 define(SM_BALANCE_BTC,'BTC balance');
 define(SM_BALANCE_USD,'USD balance');
 define(SM_CONFIRMATIONS,'Confirmations');
 define(SM_TOTAL_COINS,'Total coins in the wallet');
 define(SM_INFORMATION,'Information');
 define(SM_BLOCK_COUNT,'Block count');
 define(SM_CURRENT_DIFFICULTY,'Current difficulty');
 define(SM_CONNECTIONS,'Connections');
 define(SM_BITCOIND_VERSION,'Bitcoind server version');
 
 //About.tpl
 define(SM_DESCR_AVAIL_HERE,'Description avaible');
 define(SM_HERE,'here');
 
 //bar
 define(SM_BAR_TITLE,'BTC payment sample');
 define(SM_BAR_HOME,'Main');
 define(SM_BAR_ACCOUNT_LIST,'All accounts');
 define(SM_BAR_ABOUT,'Description');
 define(SM_BAR_CONTACT,'Contact');
 

 define(SM_THIS_IS_SAMPLE,'* This site bitpay.tk <b> is not a business service </b>! It is designed to demonstrate <b> </b> how to <b> accept payments using Bitcoin </b>. All source code can be downloaded <a href="https://github.com/Lexiks/Bitpay" target="_blank"> here </a> and totaly free to use it on your site. <br> However, the entire functional <b> is a fully working </ b> and you can  test the scripts operability  <b> </b>  (create new accounts or use available, enroll them in a virtual test BTC or by a real transfer, to test BTC-> USD checkout.  Enjoy your testing!');
 define(SM_THX_DONATE,'Thank you for your donation!');
 define(SM_THIS_IS_DEMO,'This is demo!');
 
 


?>
