<?php
   define(LANG_CANT_GET_ADDRESS,'Не удалось получить адрес, попробуте сгенерировать еге еще раз');
   define(LANG_GET_ADDRESS_AGAIN,'Получить адрес для платежа');
   define(LANG_BALANCE_SUCCESS_CHECKOUT,'Баланс успешно пополнен');
   define(LANG_BALANCE_ERROR_CHECKOUT,'Ошибка перевода баланса.');
   define(LANG_BALANCE_NOTHING_CHECKOUT,'Нечего выводить, BTC баланс = 0.');
   define(LANG_CANT_GET_BALANCE,'Не удалось получить баланс, попробуйте обновить баланс позже.');

//Тестовые
   define(LANG_TEST_COINS_OK,'Тестовые монеты зачислены');
   define(LANG_TEST_NOCOINS,'Тестовые монеты закончились');
   define(CANT_USE_MAIN_ACC,'Этот аккаунт использовать нельзя');

?>