<?php
   define(LANG_CANT_GET_ADDRESS,'Не удалось получить адрес, попробуте сгенерировать еге еще раз');
   define(LANG_GET_ADDRESS_AGAIN,'Получить адрес для платежа');
   define(LANG_BALANCE_SUCCESS_CHECKOUT,'Баланс успешно пополнен');
   define(LANG_BALANCE_ERROR_CHECKOUT,'Ошибка перевода баланса.');
   define(LANG_BALANCE_NOTHING_CHECKOUT,'Нечего выводить, BTC баланс = 0.');
   define(LANG_CANT_GET_BALANCE,'Не удалось получить баланс, попробуйте обновить баланс позже.');

//Тестовые
   define(LANG_TEST_COINS_OK,'Тестовые монеты зачислены');
   define(LANG_TEST_NOCOINS,'Тестовые монеты закончились');
   define(CANT_USE_MAIN_ACC,'Этот аккаунт использовать нельзя');
   
// Шаблоны

 //index.tpl
 define(SM_YOUR_ACCOUNT,'Ваш аккаунт');
 define(SM_CHANGE_NAME,'Изменить имя');
 define(SM_YOUR_BITPAY_ADDRES,'Ваш BitCoin адрес для оплаты');
 define(SM_YOUR_CURRENT_BTC_BALANCE,'Ваш текущий BTC баланс');
 define(SM_YOUR_CURRENT_USD_BALANCE,'Ваш текущий USD баланс');
 define(SM_REFRESH_BTC_BALANCE,'Обновить BTC баланс');
 define(SM_REFRESH_USD_BALANCE,'Обновить USD баланс');
 define(SM_GIVE_ME_TEST_COINS,'Зачислить немного тестовых монет (Переводятся внутренним переводом из аккаунта, который находится на этом же кошельке)');
 define(SM_SHOW_ALL_ACCOUNTS,'Просмотреть остатки по всем аккаунтам на кошельке');
 define(SM_REFRESH_TRANSACTIONS,'Обновить транзакции');
 define(SM_TRANSACTIONS_LIST,'Список транзакций:');
 
 //user_name.tpl
 define(SM_ENTER_YOUR_NAME,'Введите ваше имя:');
 
 //transactions
 define(SM_DATE,'Дата');
 define(SM_OPERATION,'Операция');
 define(SM_FROM,'От кого');
 define(SM_TO,'Кому');
 define(SM_SUM,'Сумма');
 define(SM_COMMENT,'Комментарий');
 define(SM_CONF,'Подтв.');
 define(SM_TRANS,'Транзакция');
 define(SM_INTERNAL_MOVE,'Внутренний перевод');
 define(SM_INTERNAL_REFILL,'Внешнее пополнение');

?>